# Standard Albumentations augmentation pipeline
train:
  - _target_: albumentations.RandomRotate90
    p: 0.5
  - _target_: albumentations.Flip
    p: 0.5
  - _target_: albumentations.HueSaturationValue
    hue_shift_limit: 20
    sat_shift_limit: 30
    val_shift_limit: 20
    p: 0.5
  - _target_: albumentations.RandomBrightnessContrast
    p: 0.3
  - _target_: albumentations.GaussNoise
    p: 0.2
  - _target_: albumentations.Resize
    height: 224
    width: 224
  - _target_: albumentations.Normalize
    mean: [0.763, 0.546, 0.570]
    std: [0.141, 0.152, 0.169]
  - _target_: albumentations.pytorch.ToTensorV2

val:
  - _target_: albumentations.Resize
    height: 224
    width: 224
  - _target_: albumentations.Normalize
    mean: [0.763, 0.546, 0.570]
    std: [0.141, 0.152, 0.169]
  - _target_: albumentations.pytorch.ToTensorV2
