"""
Integration module for seamless preprocessing with Dataset Manager and PyTorch DataLoader.
Shows how to connect the preprocessing pipeline with the unified dataset infrastructure.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

import cv2
import pandas as pd
import torch
from loguru import logger
from torch.utils.data import DataLoader, Dataset

from src.modules.preprocessing.manager import PreprocessingManager
from src.modules.preprocessing.pipeline import PipelineMetadata


class PreprocessedSkinLesionDataset(Dataset):
    """
    PyTorch Dataset with integrated preprocessing pipeline.
    Reads from unified labels generated by Dataset Manager and applies preprocessing.
    """

    def __init__(
        self,
        cleaned_csv_path: str | Path,
        preprocessing_manager: PreprocessingManager,
        indices_csv_path: str | Path | None = None,
        mode: str = "train",
        track_metadata: bool = True,
    ) -> None:
        """
        Args:
            cleaned_csv_path: Path to `labels/cleaned.csv`.
            preprocessing_manager: Initialized PreprocessingManager with built pipelines.
            indices_csv_path: Optional path to split indices (e.g., `splits/train_indices.csv`).
            mode: Pipeline mode ("train", "val", "inference").
            track_metadata: If True, collect metadata for each sample.
        """
        self.df = pd.read_csv(cleaned_csv_path)
        self.preprocessing_manager = preprocessing_manager
        self.mode = mode
        self.track_metadata = track_metadata
        self.metadata_history: list[tuple[str, PipelineMetadata | None]] = []

        if indices_csv_path:
            indices_path = Path(indices_csv_path)
            if not indices_path.exists():
                raise RuntimeError(
                    f"Split manifest file not found for mode '{mode}': {indices_path}. "
                    f"Cannot proceed without explicit split manifests."
                )
            indices_df = pd.read_csv(indices_path, header=None, names=["image_id"])
            self.df = self.df.merge(indices_df, on="image_id", how="inner")
        else:
            logger.warning(
                f"No indices_csv_path provided for mode '{mode}'. "
                f"Loading ALL {len(self.df)} records. This is only safe for full-dataset preprocessing."
            )

        self.records = self.df.to_dict("records")
        logger.info(
            f"Initialized PreprocessedSkinLesionDataset with {len(self.records)} samples "
            f"(mode: {mode})"
        )

    def __len__(self) -> int:
        return len(self.records)

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, int, str]:
        """
        Get a sample from the dataset.

        Returns:
            Tuple of (image_tensor, class_id, image_id)
        """
        record = self.records[idx]
        img_path = record["path"]
        class_id = int(record["class_id"])
        image_id = record["image_id"]

        # Load image
        img = cv2.imread(img_path)
        if img is None:
            logger.error(f"Failed to load image at {img_path}")
            raise RuntimeError(f"Failed to load image at {img_path}")

        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        # Apply preprocessing pipeline
        processed_img, metadata = self.preprocessing_manager.preprocess(
            image=img_rgb,
            mode=self.mode,
            image_id=image_id,
            track_metadata=self.track_metadata,
        )

        if self.track_metadata and metadata:
            self.metadata_history.append((image_id, metadata))

        return processed_img, class_id, image_id

    def get_metadata_history(self) -> list[tuple[str, PipelineMetadata | None]]:
        """Get accumulated metadata from preprocessing."""
        return self.metadata_history

    def clear_metadata_history(self) -> None:
        """Clear accumulated metadata."""
        self.metadata_history.clear()


def create_preprocessing_dataloader(
    cleaned_csv_path: str | Path,
    preprocessing_manager: PreprocessingManager,
    mode: str = "train",
    indices_csv_path: str | Path | None = None,
    batch_size: int = 32,
    shuffle: bool = True,
    num_workers: int = 4,
    pin_memory: bool = True,
    track_metadata: bool = False,
) -> tuple[DataLoader, PreprocessedSkinLesionDataset]:
    """
    Convenience function to create a DataLoader with preprocessing pipeline.

    Args:
        cleaned_csv_path: Path to `labels/cleaned.csv`.
        preprocessing_manager: Initialized PreprocessingManager.
        mode: Pipeline mode.
        indices_csv_path: Optional split indices path.
        batch_size: Batch size for DataLoader.
        shuffle: If True, shuffle samples.
        num_workers: Number of workers for data loading.
        pin_memory: If True, pin memory for GPU transfer.
        track_metadata: If True, track preprocessing metadata.

    Returns:
        Tuple of (DataLoader, Dataset) for access to both.
    """
    dataset = PreprocessedSkinLesionDataset(
        cleaned_csv_path=cleaned_csv_path,
        preprocessing_manager=preprocessing_manager,
        indices_csv_path=indices_csv_path,
        mode=mode,
        track_metadata=track_metadata,
    )

    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle if mode == "train" else False,
        num_workers=num_workers,
        pin_memory=pin_memory,
    )

    logger.info(
        f"Created DataLoader with {len(dataset)} samples, "
        f"batch_size={batch_size}, mode={mode}"
    )

    return dataloader, dataset


class MetadataCollector:
    """Utility class for collecting and analyzing metadata from preprocessing."""

    def __init__(self) -> None:
        self.metadata_list: list[PipelineMetadata] = []

    def add_metadata(self, metadata: PipelineMetadata) -> None:
        """Add metadata from a preprocessing execution."""
        if metadata:
            self.metadata_list.append(metadata)

    def add_from_dataset(self, dataset: PreprocessedSkinLesionDataset) -> None:
        """Collect all metadata from a dataset."""
        for _, metadata in dataset.get_metadata_history():
            self.add_metadata(metadata)

    def save_to_file(self, output_path: str | Path) -> None:
        """Save all collected metadata to a JSON file."""
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        metadata_dicts = [m.to_dict() for m in self.metadata_list]

        import json

        with open(output_path, "w") as f:
            json.dump(metadata_dicts, f, indent=2)

        logger.info(f"Saved {len(self.metadata_list)} metadata entries to {output_path}")

    def get_statistics(self) -> dict[str, Any]:
        """Get aggregated statistics from all metadata."""
        if not self.metadata_list:
            return {"total_samples": 0}

        successful = sum(1 for m in self.metadata_list if m.success)
        total_time = sum(m.total_time_ms for m in self.metadata_list)

        return {
            "total_samples": len(self.metadata_list),
            "successful": successful,
            "failed": len(self.metadata_list) - successful,
            "total_time_ms": total_time,
            "avg_time_ms": total_time / len(self.metadata_list),
            "min_time_ms": min(m.total_time_ms for m in self.metadata_list),
            "max_time_ms": max(m.total_time_ms for m in self.metadata_list),
        }

    def print_summary(self) -> None:
        """Print a human-readable summary."""
        stats = self.get_statistics()
        print("\n" + "=" * 70)
        print("Preprocessing Metadata Summary")
        print("=" * 70)
        print(f"Total Samples: {stats['total_samples']}")
        print(f"Successful: {stats['successful']}")
        print(f"Failed: {stats['failed']}")
        print(f"Total Time: {stats['total_time_ms']:.1f} ms")
        print(f"Average Time: {stats['avg_time_ms']:.1f} ms")
        print(f"Min Time: {stats['min_time_ms']:.1f} ms")
        print(f"Max Time: {stats['max_time_ms']:.1f} ms")
        print("=" * 70 + "\n")
